### ISSUE TITLE
What differs from the original version?

### ISSUE THREAD

**Issue by fuxes** [luiscoms/openshift-rabbitmq#1]
Hello Luis!,

I just found your openshift-rabbitmq image and wanted to know how did you make it work from the original rabbitmq image?

When we run the official rabbitmq image we get the following message:
error: failed switching to "rabbitmq": operation not permitted

do you know why it is? why yours does not have that issue?

Thanks in advance!

**Comment by luiscoms** [comment]
Hi @fuxes this image is an instance of rabbitmq installed on CentOS 6 to run on Openshift Origin.
The application runs with no privileged user created for this single propouse, the original image runs with root.
If your problem is on original image you should to open an issue there.

https://github.com/docker-library/rabbitmq/issues

**Comment by brice-morin** [comment]
I also had the same `switching to "rabbitmq"` issue with the official image when running on OpenShift (Minishift). @luiscoms 's image fix that issue. I guess that if you still want to use the official image, then it is an issue for the official repo, as @luiscoms pointed out.

**Comment by gdmello** [comment]
I ran into this issue while deploying the official image in kubernetes, and this was one of the few issues that came up in my search. Just adding an answer in case it helps someone else.

This issue, at least for me was caused by insufficient PodSecurityPolicy Linux Capabilities. In particular, I had `RequiredDropCapabilities: -ALL`, and since I was using docker, none of the [default](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) Linux Capabilities were enabled, causing the `PostStartupHook` script to fail. The fix - remove `RequiredDropCapabilities: -ALL`, to ensure that at least the default capability set is enabled for docker.
